### ISSUE TITLE
[Vulnerability Alert] lodash 4.17.11

### ISSUE THREAD

**Issue by TheeAndre** [appcelerator/appc-platform-sdk#79]
Hi Team,
I got this notification from my Snyk account in regards to a vulnerability in lodash 4.17.11.

Is this anything we can fix?

https://github.com/lodash/lodash/pull/4336

https://github.com/lodash/lodash/commit/1f8ea07746963a535385a5befc19fa687a627d2b

**Comment by pkclark** [comment]
We're generally not impacted by the vulnerability as this project does not use _.defaultsDeep.  Nevertheless, we'll bump to lodash 4.17.12 once it's tagged and published.  Please see the discussion in https://github.com/lodash/lodash/issues/4348.  Leaving the 3.1.1 release in https://github.com/appcelerator/appc-platform-sdk/pull/78 open to pull this in once available.  CC @feons

**Comment by pkclark** [comment]
Resolved in https://github.com/appcelerator/appc-platform-sdk/tree/3.1.1
